CREATE TABLE IF NOT EXISTS shenherenwu (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  task_no VARCHAR(32) NOT NULL,
  business_type VARCHAR(64) NOT NULL,
  business_id BIGINT NOT NULL,
  business_no VARCHAR(32),
  applicant_id BIGINT NOT NULL,
  applicant_name VARCHAR(64) NOT NULL,
  assignee_role VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS shenhejilu (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  task_id BIGINT NOT NULL,
  task_no VARCHAR(32) NOT NULL,
  auditor_id BIGINT NOT NULL,
  auditor_name VARCHAR(64) NOT NULL,
  audit_result VARCHAR(32) NOT NULL,
  audit_opinion VARCHAR(500),
  audit_time TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
