CREATE TABLE IF NOT EXISTS feiyong (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  fee_no VARCHAR(32) NOT NULL,
  patient_id BIGINT NOT NULL,
  patient_name VARCHAR(64) NOT NULL,
  business_type VARCHAR(64),
  business_id BIGINT,
  fee_item VARCHAR(128) NOT NULL,
  amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  pay_status VARCHAR(32) NOT NULL DEFAULT 'unpaid',
  pay_time TIMESTAMP,
  remark VARCHAR(500),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
